<?php
//------------------------------------------------------------------//
$router = new Router();
$router->get('/',function(){
	return view('welcome');
});
//------------------------------------------------------------------//
$router->get('/login','authController@login');
$router->post('/loginUser','authController@loginUser');
$router->get('/register','authController@register');
$router->post('/registerUser','authController@registerUser');
$router->get('/logout','authController@logout');
//------------------------------------------------------------------//
$router->get('/home','gamesController@index');
$router->post('/addGame','gamesController@addGame');
$router->post('/getGame','gamesController@getGame');
$router->post('/updateGame','gamesController@updateGame');
$router->post('/deleteGame','gamesController@deleteGame');
$router->post('/uploadGameLogo','gamesController@uploadGameLogo');
$router->post('/exportGame','gamesController@exportGame');
//------------------------------------------------------------------//
$router->get('/buildGame','buildGameController@index');
$router->get('/paint','paintController@paint');
$router->post('/saveGameSettings','buildGameController@saveGameSettings');
$router->post('/getGameSettings','buildGameController@getGameSettings');
$router->post('/saveGameStates','gameStateController@saveGameStates');
$router->post('/getGameStates','gameStateController@getGameStates');
$router->post('/getState','gameStateController@getState');
$router->post('/getNextState','gameStateController@getNextState');
$router->post('/deleteGameState','gameStateController@deleteGameState');
//------------------------------------------------------------------//
$router->post('/saveUserFiles','userFilesController@saveUserFiles');
$router->post('/getUserImages','userFilesController@getUserImages');
$router->post('/setStateBackground','gameStateController@setStateBackground');
$router->post('/getStateBackground','gameStateController@getStateBackground');
//------------------------------------------------------------------//
$router->post('/savePaint2Image','paintController@savePaint2Image');
$router->post('/deletePaint','paintController@deletePaint');
$router->get('/editPaint','paintController@editPaint');
$router->post('/getUserPaints','paintController@getUserPaintsList');
$router->post('/getUserPaintsImages','paintController@getUserPaintsImages');
//------------------------------------------------------------------//
$router->post('/uploadUserFile','userFilesController@uploadUserFile');
//------------------------------------------------------------------//
$router->post('/savePixel','pixelController@savePixel');
$router->post('/getStatePixels','pixelController@getStatePixels');
$router->post('/getPixelData','pixelController@getPixelData');
$router->post('/getPixels','pixelController@getPixels');
//------------------------------------------------------------------//
$router->post('/saveGameKeys','gameKeysController@saveGameKeys');
$router->post('/getGameKeys','gameKeysController@getGameKeys');
//------------------------------------------------------------------//
$router->notFound_404();